# Etapa única (PHP-FPM com MySQL e SQLite)
FROM php:8.3-fpm

# Instala dependências do sistema e extensões PHP
RUN apt-get update && apt-get install -y \
    git unzip libpng-dev libonig-dev libxml2-dev curl \
    libzip-dev libjpeg-dev libfreetype6-dev libssl-dev \
    default-mysql-client sqlite3 libsqlite3-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql pdo_sqlite mbstring exif pcntl bcmath gd zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instala Composer
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN composer install --no-dev --optimize-autoloader \
    && php artisan config:cache || true

EXPOSE 9000
CMD ["php-fpm"]
